MVC/Models/CourseResult.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC.Models
{
    public class CourseResult
    {
        public int Id { get; set; }
        [Required]
        [Range(0,100, ErrorMessage = "Degree must be from 0 to 100")]
        public decimal Degree { get; set; }
        [ForeignKey("Trainee")]
        [Required]
        [Display(Name ="Trainee")]
        public int TranieeId { get; set; }
        public Trainee Trainee { get; set; }
        [ForeignKey("Course")]
        [Required]
        [Display(Name ="Course")]
        public int CourseId { get; set; }
        public Course Course { get; set; }
    }
}

MVC/Controllers/CourseResultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC.Interfaces;
using MVC.Models;
using System.Threading.Tasks;

namespace MVC.Controllers
{
    [Authorize]
    public class CourseResultController : Controller
    {
        private readonly ICourseResultRepository _courseResultRepository;
        private readonly ICourseRepository _courseRepository;
        private readonly ITraineeRepository _traineeRepository;
        public CourseResultController(ICourseResultRepository courseResultRepository, ICourseRepository courseRepository, ITraineeRepository traineeRepository)
        {
            _courseResultRepository = courseResultRepository;
            _courseRepository = courseRepository;
            _traineeRepository = traineeRepository;
        }

        public async Task<IActionResult> Index()
        {
            var courseResults=await _courseResultRepository.GetAll();
            return View(courseResults);
        }
        public async Task<IActionResult> Detail(int id)
        {
            return View(await _courseResultRepository.GetById(id));
        }
        public async Task<IActionResult> GetEditView(int id)
        {
            var courseResult=await _courseResultRepository.GetById(id);
            var courses=await _courseRepository.GetAll();
            var trainees=await _traineeRepository.GetAll();
            ViewBag.Courses = courses;
            ViewBag.Trainees = trainees;
            return View("Edit",courseResult);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,CourseResult newCourseResult)
        {
            if (ModelState.IsValid)
            {
                var course = await _courseRepository.GetById(newCourseResult.CourseId);
                if (newCourseResult.Degree > course.Degree)
                    ModelState.AddModelError("", $"Degree must be less than or equal {course.Degree}");
                else
                {
                    await _courseResultRepository.Update(id, newCourseResult);
                    return RedirectToAction("Index");
                }
            }
            var courses = await _courseRepository.GetAll();
            var trainees = await _traineeRepository.GetAll();
            ViewBag.Courses = courses;
            ViewBag.Trainees = trainees;
            return View("Edit", newCourseResult);
        }
        public async Task<IActionResult> GetView()
        {
            var courses = await _courseRepository.GetAll();
            var trainees = await _traineeRepository.GetAll();
            ViewBag.Courses = courses;
            ViewBag.Trainees = trainees;
            return View("AddNew");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCourseResult(CourseResult newCourseResult)
        {
            if (ModelState.IsValid)
            {
                var course = await _courseRepository.GetById(newCourseResult.CourseId);
                if (newCourseResult.Degree > course.Degree)
                    ModelState.AddModelError("", $"Degree must be less than or equal {course.Degree}");
                else
                {
                    await _courseResultRepository.Insert(newCourseResult);
                    return RedirectToAction("Index");
                }
            }
            var courses = await _courseRepository.GetAll();
            var trainees = await _traineeRepository.GetAll();
            ViewBag.Courses = courses;
            ViewBag.Trainees = trainees;
            return View("AddNew",newCourseResult);
        }
        public async Task<IActionResult> DeleteCourseResult(int id)
        {
            await _courseResultRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MVC/Views/CourseResult/AddNew.cshtml
@model CourseResult
@{
    SelectList selectListTrainees = new SelectList(ViewBag.Trainees, "Id", "Name");
    SelectList selectListCourses = new SelectList(ViewBag.Courses, "Id", "Name");
}
<form asp-action="AddCourseResult" asp-controller="courseresult" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col">
            <label asp-for="Degree"></label>
            <input class="form-control" placeholder="Degree" asp-for="Degree">
            <span asp-validation-for="Degree" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="TranieeId" for="inputState"></label>
            <select asp-for="TranieeId" asp-items="selectListTrainees" id="inputState" class="form-control">
            </select>
            <span asp-validation-for="TranieeId" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="CourseId" for="inputState"></label>
            <select asp-for="CourseId" asp-items="selectListCourses" id="inputState" class="form-control">
            </select>
            <span asp-validation-for="CourseId" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MVC/Views/CourseResult/Detail.cshtml
@model CourseResult
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="/Images/@Model.Trainee.Image" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Trainee.Name</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Course: @Model.Course.Name</li>
        <li class="list-group-item">Degree: @Model.Degree</li>
    </ul>
</div>

MVC/Views/CourseResult/Edit.cshtml
@model CourseResult
@{
    SelectList selectListTrainees = new SelectList(ViewBag.Trainees, "Id", "Name");
    SelectList selectListCourses = new SelectList(ViewBag.Courses, "Id", "Name");
}
<form asp-action="Edit" asp-controller="CourseResult" asp-route-id="@Model.Id" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col">
            <label asp-for="Degree"></label>
            <input class="form-control" placeholder="Degree" asp-for="Degree">
            <span asp-validation-for="Degree" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="TranieeId" for="inputState"></label>
            <select asp-for="TranieeId" asp-items="selectListTrainees" id="inputState" class="form-control">
            </select>
            <span asp-validation-for="TranieeId" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="CourseId" for="inputState"></label>
            <select asp-for="CourseId" asp-items="selectListCourses" id="inputState" class="form-control">
            </select>
            <span asp-validation-for="CourseId" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MVC/Views/CourseResult/Index.cshtml
@model List<CourseResult>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Trainee</th>
            <th scope="col">Course</th>
            <th scope="col">Degree</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Trainee.Name</td>
                <td>@item.Course.Name</td>
                <td>@item.Degree</td>
                <td><a href="/courseresult/detail/@item.Id"><button type="button" class="btn btn-primary">Detail</button></a> </td>
                <td><a href="/courseresult/GetEditView/@item.Id"><button type="button" class="btn btn-primary">Edit</button></a> </td>
                <td><a href="/courseresult/DeletecourseResult/@item.Id"><button type="button" class="btn btn-danger">Delete</button></a> </td>
            </tr>
        }
    </tbody>
</table>
<a href="/courseresult/getview" style="margin-top:10px"> <button type="button" class="btn btn-primary">Add</button></a>