MVC/Models/Trainee.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC.Models
{
    public class Trainee
    {
        public int Id { get; set; }
        [Required]
        [MinLength(1,ErrorMessage ="Name must be more than 1")]
        [MaxLength(50, ErrorMessage = "Name must be less than 50")]
        public string Name { get; set; }
        [Required]
        public string Image { get; set; }
        [Required]
        [MaxLength(255, ErrorMessage = "Name must be less than 255")]
        [MinLength(1, ErrorMessage = "Name must be more than 1")]
        public string Address { get; set; }
        [Required]
        [Range(0.1, 4,ErrorMessage ="Grade must be from 0.1 to 4")]
        public decimal Grade { get; set; }
        [ForeignKey("Department")]
        [Display(Name = "Department")]
        [Required]
        [Range(1, int.MaxValue,ErrorMessage ="DepartmentId must be more than 0")]
        public int DepartNum { get; set; }
        public Department Department { get; set; }
      
    }
}

MVC/Controllers/TraineeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC.Data;
using MVC.Dtos;
using MVC.Interfaces;
using MVC.Models;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Controllers
{
    [Authorize]
    public class TraineeController : Controller
    {
        private readonly ITraineeRepository _traineeRepository;
        private readonly IDepartmentRepository _departmentRepository;
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;
        public TraineeController(ITraineeRepository traineeRepository, ApplicationDbContext context, IDepartmentRepository departmentRepository, IMapper mapper)
        {
            _traineeRepository = traineeRepository;
            _context = context;
            _departmentRepository = departmentRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Detail(int id)
        {
            var trainee=await _traineeRepository.GetById(id);
            var deptName=trainee.Department.Name;
            ViewBag.deptName = deptName;   
            return View(trainee);
        }
        public async Task<IActionResult> Index()
        {
            var trainees = await _traineeRepository.GetAll();
            return View(trainees);
        }
      
        public async Task<IActionResult> GetView()
        {
            var departments=await _departmentRepository.GetAll();
            ViewBag.Depts= departments;
            return View("AddNew");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTrainee(TraineeDto trainee)
        {
            if(ModelState.IsValid)
            {
               await _traineeRepository.Insert(trainee);
                return RedirectToAction("Index");
            }
            var departments =await _departmentRepository.GetAll();
            ViewBag.Depts= departments;
            return View("AddNew", trainee);
        }
        public async Task<IActionResult> GetEditView(int id)
        {
            var trainee=await _traineeRepository.GetById(id);
            var dto=_mapper.Map<TraineeDto>(trainee);
            var departments = await _departmentRepository.GetAll();
            ViewBag.Depts= departments;
            ViewBag.Trainee = trainee;
            return View("Edit", dto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,TraineeDto dto)
        {
            if (ModelState.IsValid)
            {
                await _traineeRepository.Update(id,dto);
                return RedirectToAction("Index");
            }
            ViewBag.Depts = await _departmentRepository.GetAll();
            ViewBag.Trainee = _traineeRepository.GetById(id);
            return View("Edit", dto);
        }
        public async Task<IActionResult> DeleteTrainee(int id)
        {
            if (await _context.CoursesResults.AnyAsync(x => x.TranieeId == id))
                return RedirectToAction("Index");
            
           await _traineeRepository.Delete(id);
            return RedirectToAction("Index");
        }
     
    }
}

MVC/Views/Trainee/AddNew.cshtml
@model TraineeDto
@{
    SelectList selectListItems = new SelectList(ViewBag.Depts, "Id", "Name");
}
<form asp-action="AddTrainee" asp-controller="trainee" method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col">
            <label asp-for="Name"></label>
            <input  class="form-control" placeholder="Name" asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Address"></label>
            <input class="form-control" placeholder="Address" asp-for="Address">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="Image"></label>
            <input  class="form-control" placeholder="Image" required asp-for="Image">
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Grade"></label>
            <input class="form-control" placeholder="Grade" asp-for="Grade">
            <span asp-validation-for="Grade" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="DepartNum" for="inputState"></label>
            <select asp-items="selectListItems" asp-for="DepartNum" id="inputState" class="form-control">
              
            </select>
            <span asp-validation-for="DepartNum" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />

}

MVC/Views/Trainee/Detail.cshtml
@model Trainee
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="/Images/@Model.Image" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Address: @Model.Address</li>
        <li class="list-group-item">Grade: @Model.Grade</li>
        <li class="list-group-item">Department: @ViewBag.deptName</li>
    </ul>
</div>

MVC/Views/Trainee/Edit.cshtml
@model TraineeDto
@{
    SelectList selectListItems = new SelectList(ViewBag.Depts, "Id", "Name");
}
<form asp-action="Edit" asp-controller="Trainee" asp-route-id="@ViewBag.Trainee.Id" method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col">
            <label asp-for="Name"></label>
            <input  class="form-control" placeholder="Name" asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Address" ></label>
            <input  class="form-control" placeholder="Address" asp-for="Address">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="Image"></label>
            <input class="form-control" placeholder="Image" asp-for="Image">
            <img src="/Images/@ViewBag.Trainee.Image" style="height:75px;width:75px;margin:10px 5px;" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Grade"></label>
            <input class="form-control" placeholder="Grade" asp-for="Grade">
            <span asp-validation-for="Grade" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="DepartNum" for="inputState"></label>
            <select asp-for="DepartNum" asp-items="selectListItems" id="inputState" class="form-control">
               
            </select>
            <span asp-validation-for="DepartNum"class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MVC/Views/Trainee/Index.cshtml
@model List<Trainee>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col">Grade</th>
            <th scope="col">Image</th>
            <th scope="col">Department</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@item.Address</td>
                <td>@item.Grade</td>
                <td><img src="/Images/@item.Image" style="height:50px;width:50px" /></td>
                <td>@item.Department.Name</td>
                <td><a href="/trainee/detail/@item.Id"><button type="button" class="btn btn-primary">Detail</button></a> </td>
                <td><a href="/trainee/GetEditView/@item.Id"><button type="button" class="btn btn-primary">Edit</button></a> </td>
                <td><a href="/trainee/DeleteTrainee/@item.Id"><button type="button" class="btn btn-danger">Delete</button></a> </td>
            </tr>
        }
    </tbody>
</table>
<a href="/trainee/getview" style="margin-top:10px"> <button type="button" class="btn btn-primary">Add</button></a>