MVC/Models/Course.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Attribute;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC.Models
{
    public class Course
    {
        public int Id { get; set; }
        [Required]
        [MinLength(1, ErrorMessage = "Name must be more than 1")]
        [MaxLength(50, ErrorMessage = "Name must be less than 50")]
        public string Name { get; set; }
        [Required]
        [Range(20, 100, ErrorMessage = "Degree must be from 20 to 100")]
        public int Degree { get; set; }
        [Required]
        [Range(10, 50, ErrorMessage = "Degree must be from 10 to 50")]
        [Degree]
        [Remote("CheckDegree","validation",AdditionalFields ="Degree",ErrorMessage = "minDegree must be half of degree")]
        public int MinDegree { get; set; }
        [ForeignKey("Department")]
        [Display(Name ="Department")]
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "DepartmentId must be more than 0")]
        public int DepartNum { get; set; }
        public Department Department { get; set; }
    }
}

MVC/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC.Data;
using MVC.Interfaces;
using MVC.Models;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
       private readonly ICourseRepository _courseRepository;
       private readonly IDepartmentRepository _departmentRepository;
        public CourseController(ICourseRepository courseRepository, IDepartmentRepository departmentRepository)
        {
            _courseRepository = courseRepository;
            _departmentRepository = departmentRepository;
        }

        public async Task<IActionResult> Index()
        {
            var courses =await _courseRepository.GetAll();
            return View(courses);
        }
        public async Task<IActionResult> Detail(int id)
        {
            var course=await _courseRepository.GetById(id);
            var deptName=course.Department.Name;
            ViewBag.deptName = deptName;
            return View(course);
        }
        public async Task<IActionResult> GetEditView(int id)
        {
            var course = await _courseRepository.GetById(id);
            var depts=await _departmentRepository.GetAll();
            ViewBag.depts = depts;
            return View("Edit",course);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,Course course)
        {
            if(ModelState.IsValid)
            {
                await _courseRepository.Update(id, course);
                return RedirectToAction("Index");
            }
            var depts = await _departmentRepository.GetAll();
            ViewBag.depts = depts;
            return View("Edit", course);
        }
        public async Task<IActionResult> GetView()
        {
            var depts =await _departmentRepository.GetAll();
            ViewBag.depts = depts;
            return View("AddNew");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCourse(Course newCourse) 
        {
            if(ModelState.IsValid)
            {
                await _courseRepository.Insert(newCourse);
                return RedirectToAction("Index");
            }
            var depts = await _departmentRepository.GetAll();
            ViewBag.depts = depts;
            return View("AddNew", newCourse);
        }
        public async Task<IActionResult> Deletecourse(int id)
        {
            await _courseRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> GetCoursesByDeptId(int deptId)
        {
            var courses=await _courseRepository.GetByDeptId(deptId);
            return PartialView("_CoursesByDeptIdPartial", courses);
        }
       
    }
}

MVC/Views/Course/AddNew.cshtml
@model Course
@{
    SelectList selectListItems = new SelectList(ViewBag.depts, "Id", "Name");
}
<form asp-action="AddCourse" asp-controller="course" method="post">
    <div class="row">
        <div class="col">
            <label asp-for="Name"></label>
            <input  class="form-control" placeholder="Name" asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Degree"></label>
            <input  class="form-control" placeholder="Degree" asp-for="Degree">
            <span asp-validation-for="Degree" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="MinDegree"></label>
            <input  class="form-control" placeholder="MinDegree" asp-for="MinDegree">
            <span asp-validation-for="MinDegree" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="DepartNum" for="inputState"></label>
            <select asp-for="DepartNum" asp-items="selectListItems" id="inputState" class="form-control">
             
            </select>
            <span asp-validation-for="DepartNum" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MVC/Views/Course/Detail.cshtml
@model Course
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Address: @Model.Degree</li>
        <li class="list-group-item">Grade: @Model.MinDegree</li>
        <li class="list-group-item">Department: @ViewBag.deptName</li>
    </ul>
</div>

MVC/Views/Course/Edit.cshtml
@model Course
@{
    SelectList selectListItems = new SelectList(ViewBag.depts, "Id", "Name");
}
<form asp-action="Edit" asp-controller="Course" asp-route-id="@Model.Id" method="post">
    <div class="row">
        <div class="col">
            <label asp-for="Name"></label>
            <input  class="form-control" placeholder="Name" asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Degree"></label>
            <input class="form-control" placeholder="Degree" asp-for="Degree">
            <span asp-validation-for="Degree" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="MinDegree"></label>
            <input  class="form-control" placeholder="MinDegree" asp-for="MinDegree">
            <span asp-validation-for="MinDegree" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="DepartNum" for="inputState"></label>
            <select asp-for="DepartNum" asp-items="selectListItems" id="inputState" class="form-control">
            </select>
            <span asp-validation-for="DepartNum" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MVC/Views/Course/Index.cshtml
@model List<Course>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Degree</th>
            <th scope="col">MinDegree</th>
            <th scope="col">Department</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@item.Degree</td>
                <td>@item.MinDegree</td>
                <td>@item.Department.Name</td>
                <td><a href="/course/detail/@item.Id"><button type="button" class="btn btn-primary">Detail</button></a> </td>
                <td><a href="/course/GetEditView/@item.Id"><button type="button" class="btn btn-primary">Edit</button></a> </td>
                <td><a href="/course/Deletecourse/@item.Id"><button type="button" class="btn btn-danger">Delete</button></a> </td>
            </tr>
        }
    </tbody>
</table>
<a href="/course/getview" style="margin-top:10px"> <button type="button" class="btn btn-primary">Add</button></a>

MVC/Views/Course/_CoursesByDeptIdPartial.cshtml
@model List<Course>

@foreach(var course in Model)
{
    <option value="@course.Id" >@course.Name</option>
}