MVC/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace MVC.Models
{
    public class Department
    {
        public int Id { get; set; }
        [Required]
        [MinLength(1, ErrorMessage = "Name must be more than 1")]
        [MaxLength(50, ErrorMessage = "Name must be less than 50")]
        public string Name { get; set; }
        [Required]
        [MinLength(1, ErrorMessage = "Name must be more than 1")]
        [MaxLength(50, ErrorMessage = "Name must be less than 50")]
        public string Manager { get; set; }
    }
}

MVC/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC.Data;
using MVC.Interfaces;
using MVC.Models;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IDepartmentRepository _departmentRepository;

        public DepartmentController(ApplicationDbContext context, IDepartmentRepository departmentRepository)
        {
            _context = context;
            _departmentRepository = departmentRepository;
        }

        public async Task<IActionResult> Index()
        {
            var depts= await _departmentRepository.GetAll();
            return View(depts);
        }
        public async Task<IActionResult> Detail(int id)
        {
            var department =await _departmentRepository.GetById(id);
            return View(department);
        }
        public IActionResult GetView()
        {
            return View("AddNew");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddDepartment(Department department)
        {
            if(ModelState.IsValid)
            {
                await _departmentRepository.Insert(department);
                return RedirectToAction("Index");
            }
            return View("AddNew",department);
        }
        public async Task<IActionResult> GetEditView(int id)
        {
            var dept=await _departmentRepository.GetById(id);
            return View("Edit",dept);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,Department dept)
        {
            if (ModelState.IsValid)
            {
                await _departmentRepository.Update(id, dept);
                return RedirectToAction("Index");
            }
            return View("Edit",dept);
        }
        public async Task<IActionResult> DeleteDepartment(int id)
        {
            if (_context.Instructors.Any(i => i.DepartId == id))
                return RedirectToAction("Index");
            await _departmentRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MVC/Views/Department/AddNew.cshtml
@model Department

<form asp-action="AddDepartment" asp-controller="Department" method="post">
    <div class="row">
        <div class="col">
            <label asp-for="Name"></label>
            <input class="form-control" placeholder="Name" asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Manager"></label>
            <input class="form-control" placeholder="Manager" asp-for="Manager">
            <span asp-validation-for="Manager" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MVC/Views/Department/Detail.cshtml
@model Department
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Manager: @Model.Manager</li>
    </ul>
</div>

MVC/Views/Department/Edit.cshtml
@model Department

<form asp-action="Edit" asp-controller="Department" asp-route-id="@Model.Id" method="post">
    <div class="row">
        <div class="col">
            <label asp-for="Name"></label>
            <input class="form-control" placeholder="Name" asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Manager"></label>
            <input class="form-control" placeholder="Manager" asp-for="Manager">
            <span asp-validation-for="Manager" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MVC/Views/Department/Index.cshtml
@model List<Department>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Manager</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@item.Manager</td>
                <td><a href="/department/detail/@item.Id"><button type="button" class="btn btn-primary">Detail</button></a> </td>
                <td><a href="/department/GetEditView/@item.Id"><button type="button" class="btn btn-primary">Edit</button></a> </td>
                <td><a href="/department/Deletedepartment/@item.Id"><button type="button" class="btn btn-danger">Delete</button></a> </td>
            </tr>
        }
    </tbody>
</table>
<a href="/department/getview" style="margin-top:10px"> <button type="button" class="btn btn-primary">Add</button></a>